# Generated by Django 5.0.1 on 2024-01-08 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_infor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="person",
            table="my_infor",
        ),
        migrations.AlterModelTable(
            name="skill",
            table="skill",
        ),
    ]
