# Generated by Django 5.0.1 on 2024-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_infor", "0006_alter_myinfor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myinfor",
            name="date",
            field=models.TimeField(),
        ),
    ]
