# Generated by Django 5.0.1 on 2024-01-08 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_infor", "0009_alter_myinfor_date"),
    ]

    operations = []
