# Generated by Django 5.0.1 on 2024-01-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_infor", "0011_myeducation_date_projectframework_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myproject",
            name="date",
            field=models.DateField(default="2022-01-01"),
        ),
        migrations.AddField(
            model_name="myproject",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="myproject",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
