# Generated by Django 5.0.1 on 2024-01-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_infor", "0012_myproject_date_myproject_description_myproject_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myexperience",
            name="time",
        ),
        migrations.AddField(
            model_name="myexperience",
            name="date",
            field=models.DateField(default="2022-01-01"),
        ),
        migrations.AddField(
            model_name="myexperience",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
