# Generated by Django 5.0.1 on 2024-01-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_infor", "0013_remove_myexperience_time_myexperience_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myproject",
            name="description",
            field=models.TextField(),
        ),
    ]
